_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: fr
uuid: c6bfad94-366b-4b60-9fb1-6bab1870703c
name: 'Pharmacie Rabe'
mail: miandrilala9@yahoo.fr
slogan: ''
page:
  403: /user/login
  404: ''
  front: /admin/articles
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
