_core:
  default_config_hash: t7clj3mzmOGrXX0HuCH5usf0vEqRtnMTBFVBIEmZ5pc
langcode: fr
first_day: 1
country:
  default: MG
timezone:
  default: Indian/Antananarivo
  user:
    configurable: true
    default: 0
    warn: false
