label: Templating
display:
  default:
    display_title: Default
    display_options:
      title: Templating
      fields:
        title:
          label: Title
          separator: ', '
        field_templating_bundle:
          label: Bundle
          separator: ', '
        field_templating_entity_type:
          label: Entitype
          separator: ', '
        field_templating_theme:
          label: Theme
          separator: ', '
        operations:
          label: 'Operations links'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        status:
          expose:
            label: 'Published status'
        keys:
          expose:
            label: 'Search Keywords'
  page_1:
    display_title: Page
